// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplicationLists() {
  return window['go']['main']['App']['ApplicationLists']();
}

export function CancelSync() {
  return window['go']['main']['App']['CancelSync']();
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function DownloadApplication(arg1) {
  return window['go']['main']['App']['DownloadApplication'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function LastSync() {
  return window['go']['main']['App']['LastSync']();
}

export function LaunchApplication(arg1, arg2) {
  return window['go']['main']['App']['LaunchApplication'](arg1, arg2);
}

export function LoadCatalog() {
  return window['go']['main']['App']['LoadCatalog']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LocalAppsBasePath() {
  return window['go']['main']['App']['LocalAppsBasePath']();
}

export function RepairApplication(arg1) {
  return window['go']['main']['App']['RepairApplication'](arg1);
}

export function UninstallApplication(arg1) {
  return window['go']['main']['App']['UninstallApplication'](arg1);
}

export function UpdateApplication(arg1) {
  return window['go']['main']['App']['UpdateApplication'](arg1);
}
