// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appstate} from '../models';
import {appcatalog} from '../models';
import {settings} from '../models';

export function AppVersion():Promise<string>;

export function ApplicationLists():Promise<appstate.Lists>;

export function CancelSync():Promise<boolean>;

export function ConfigPath():Promise<string>;

export function DownloadApplication(arg1:string):Promise<void>;

export function Health():Promise<string>;

export function LastSync():Promise<string>;

export function LaunchApplication(arg1:string,arg2:string):Promise<void>;

export function LoadCatalog():Promise<appcatalog.Catalog>;

export function LoadSettings():Promise<settings.Config>;

export function LocalAppsBasePath():Promise<string>;

export function RepairApplication(arg1:string):Promise<void>;

export function UninstallApplication(arg1:string):Promise<void>;

export function UpdateApplication(arg1:string):Promise<void>;
